# Pandas-on-Spark

In [1]:
from pyspark.sql import SparkSession
import pandas as pd
import numpy as np
import pyspark.pandas as ps
from pyspark.sql.functions import *
ps.set_option('compute.fail_on_ansi_mode', False)

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(
WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/22 15:46:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/22 15:46:11 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/03/22 15:46:11 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.

In [2]:
spark = SparkSession.builder.appName('my_app').config("spark.sql.ansi.enabled", "false").getOrCreate()

26/03/22 15:46:13 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [3]:
pdf = pd.read_csv("weekly_nfl_data.csv")
psdf = ps.from_pandas(pdf)
psdf.head()

26/03/22 15:46:19 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

In [4]:
psdf.dtypes

player_id                       object
player_name                     object
player_display_name             object
position                        object
position_group                  object
headshot_url                    object
recent_team                     object
season                           int64
week                             int64
season_type                     object
opponent_team                   object
completions                      int64
attempts                         int64
passing_yards                  float64
passing_tds                      int64
interceptions                  float64
sacks                          float64
sack_yards                     float64
sack_fumbles                     int64
sack_fumbles_lost                int64
passing_air_yards              float64
passing_yards_after_catch      float64
passing_first_downs            float64
passing_epa                    float64
passing_2pt_conversions          int64
pacr                           float64
dakota                         float64
carries                          int64
rushing_yards                  float64
rushing_tds                      int64
rushing_fumbles                float64
rushing_fumbles_lost           float64
rushing_first_downs            float64
rushing_epa                    float64
rushing_2pt_conversions          int64
receptions                       int64
targets                          int64
receiving_yards                float64
receiving_tds                    int64
receiving_fumbles              float64
receiving_fumbles_lost         float64
receiving_air_yards            float64
receiving_yards_after_catch    float64
receiving_first_downs          float64
receiving_epa                  float64
receiving_2pt_conversions        int64
racr                           float64
target_share                   float64
air_yards_share                float64
wopr                           float64
special_teams_tds              float64
fantasy_points                 float64
fantasy_points_ppr             float64
dtype: object

In [5]:
new_df = psdf[(psdf['season'] >=2005) & (psdf['season'] <=2023) & (psdf['season_type'] == 'REG') & (psdf['position'] == 'QB')]
new_df = new_df[['player_display_name','season','week','completions','attempts','passing_yards','passing_tds','interceptions']]
new_df.head()

      player_display_name  season  week  completions  attempts  passing_yards  passing_tds  interceptions
29406          Tony Banks    2005    17           14        25          173.0            1            2.0
29426       Charlie Batch    2005     9            9        16           65.0            0            1.0
29427       Charlie Batch    2005    10           13        19          150.0            0            0.0
29428       Charlie Batch    2005    16            1         1           31.0            1            0.0
29447          Jeff Blake    2005     2            1         1           11.0            0            0.0

In [6]:
new_df_stats = new_df.groupby(['player_display_name','season']).agg(['sum', 'mean'])

In [7]:
new_df_stats['completion_percentage'] = (new_df_stats['completions']['sum'])/(new_df_stats['attempts']['sum'])
new_df_stats['td_int_ratio'] =  (new_df_stats['passing_tds']['sum'])/(new_df_stats['interceptions']['sum'])
new_df_stats.head()

                           week            completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                            sum       mean         sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jeff Blake          2005     19   9.500000           8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.000000              0.888889          inf
Daunte Culpepper    2005     31   4.428571         139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286              0.643519     0.500000
Kerry Collins       2005    134   8.933333         302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667              0.533569     1.538462
Tony Banks          2005     17  17.000000          14  14.000000       25  25.000000         173.0  173.000000           1  1.000000           2.0  2.000000              0.560000     0.500000
Charlie Batch       2005     35  11.666667          23   7.666667       36  12.000000         246.0   82.000000           1  0.333333           1.0  0.333333              0.638889     1.000000

In [8]:
attempts_over_50 = new_df_stats[new_df_stats['attempts']['sum'] >= 50]
attempts_over_50.head()

                           week            completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                            sum       mean         sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Daunte Culpepper    2005     31   4.428571         139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286              0.643519     0.500000
Kerry Collins       2005    134   8.933333         302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667              0.533569     1.538462
Jeff Garcia         2005     69  11.500000         102  17.000000      173  28.833333         937.0  156.166667           3  0.500000           6.0  1.000000              0.589595     0.500000
Brett Favre         2005    147   9.187500         372  23.250000      607  37.937500        3881.0  242.562500          20  1.250000          29.0  1.812500              0.612850     0.689655
Todd Bouman         2005     60  12.000000          68  13.600000      122  24.400000         722.0  144.400000           2  0.400000           7.0  1.400000              0.557377     0.285714

In [9]:
descending_by_cp = new_df_stats.sort_values(by='completion_percentage', ascending=False)
descending_by_cp['completion_percentage'][:40]

player_display_name  season
Anthony Wright       2006      1.000000
Matt Gutierrez       2007      1.000000
Dennis Dixon         2008      1.000000
Matt Gutierrez       2009      1.000000
Brad Smith           2009      1.000000
Billy Volek          2010      1.000000
Jordan Palmer        2010      1.000000
Brian Hoyer          2011      1.000000
Tyrod Taylor         2011      1.000000
Derek Anderson       2012      1.000000
Trent Edwards        2012      1.000000
Chase Daniel         2012      1.000000
Colt McCoy           2013      1.000000
Tarvaris Jackson     2014      1.000000
Matt Moore           2015      1.000000
Chase Daniel         2015      1.000000
Scott Tolzien        2015      1.000000
Ryan Nassib          2015      1.000000
Chase Daniel         2016      1.000000
Taylor Heinicke      2017      1.000000
Alex Tanney          2019      1.000000
AJ McCarron          2020      1.000000
Easton Stick         2020      1.000000
C.J. Beathard        2021      1.000000
Brandon Allen        2022      1.000000
Sean Clifford        2023      1.000000
Mike Glennon         2016      0.909091
Kyle Orton           2012      0.900000
Jeff Blake           2005      0.888889
Quinn Gray           2008      0.875000
Josh Johnson         2010      0.875000
Sean Mannion         2015      0.857143
Nick Mullens         2022      0.840000
Kellen Clemens       2015      0.833333
Brian Hoyer          2022      0.833333
Mike White           2023      0.833333
Nate Sudfeld         2017      0.826087
Landry Jones         2017      0.821429
Luke McCown          2015      0.820513
Brian Hoyer          2021      0.818182
Name: completion_percentage, dtype: float64

In [10]:
ascending_by_td = new_df_stats.sort_values(by='td_int_ratio')
ascending_by_td['td_int_ratio'][:40]

player_display_name  season
Koy Detmer           2005      0.0
Jon Kitna            2005      0.0
Cody Pickett         2005      0.0
Philip Rivers        2005      0.0
Matt Mauck           2005      0.0
Aaron Rodgers        2005      0.0
Brooks Bollinger     2006      0.0
Brett Basanez        2006      0.0
Brodie Croyle        2006      0.0
Billy Volek          2007      0.0
Brock Berlin         2007      0.0
Charlie Frye         2007      0.0
Bruce Gradkowski     2007      0.0
Matt Cassel          2007      0.0
Trent Green          2008      0.0
Tyler Thigpen        2007      0.0
Ken Dorsey           2008      0.0
Andrew Walter        2008      0.0
Bruce Gradkowski     2008      0.0
Kellen Clemens       2008      0.0
Jordan Palmer        2008      0.0
Kevin Kolb           2008      0.0
Mark Brunell         2009      0.0
Chris Simms          2009      0.0
Rex Grossman         2009      0.0
Matt Leinart         2009      0.0
Caleb Hanie          2009      0.0
Drew Stanton         2009      0.0
Troy Smith           2009      0.0
Matt Flynn           2009      0.0
Brian Brohm          2009      0.0
Curtis Painter       2009      0.0
Todd Collins         2010      0.0
David Carr           2010      0.0
Kyle Boller          2010      0.0
Brodie Croyle        2010      0.0
Dennis Dixon         2010      0.0
Richard Bartel       2010      0.0
Brian Brohm          2010      0.0
Levi Brown           2010      0.0
Name: td_int_ratio, dtype: float64

# Spark SQL

In [11]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('my_app').config("spark.sql.ansi.enabled", "false").getOrCreate()

In [12]:
sql_df = spark.read.load("weekly_nfl_data.csv",
                     format="csv", 
                     sep=",", 
                     inferSchema="true", 
                     header="true")

In [13]:
sql_df.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

In [14]:
sql_df.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

In [15]:
sql_short = sql_df.select(['player_display_name','season', 'week', 'completions','attempts','passing_yards','passing_tds','interceptions']).filter((sql_df.season.between(2005,2023)) & (sql_df.position == 'QB') & (sql_df.season_type == 'REG'))
sql_short.show()

+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|player_display_name|season|week|completions|attempts|passing_yards|passing_tds|interceptions|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|         Tony Banks|  2005|  17|         14|      25|        173.0|          1|          2.0|
|      Charlie Batch|  2005|   9|          9|      16|         65.0|          0|          1.0|
|      Charlie Batch|  2005|  10|         13|      19|        150.0|          0|          0.0|
|      Charlie Batch|  2005|  16|          1|       1|         31.0|          1|          0.0|
|         Jeff Blake|  2005|   2|          1|       1|         11.0|          0|          0.0|
|         Jeff Blake|  2005|  17|          7|       8|         44.0|          1|          0.0|
|       Drew Bledsoe|  2005|   1|         18|      24|        226.0|          3|          0.0|
|       Drew Bledsoe|  2005|   2|         21|      36|        261.0|          1|          0.0|
|       Drew Bledsoe|  2005|   3|         24|      38|        363.0|          2|          2.0|
|       Drew Bledsoe|  2005|   4|         11|      26|        212.0|          1|          1.0|
|       Drew Bledsoe|  2005|   5|         24|      35|        289.0|          3|          0.0|
|       Drew Bledsoe|  2005|   6|         26|      37|        312.0|          1|          1.0|
|       Drew Bledsoe|  2005|   7|         13|      24|        136.0|          1|          2.0|
|       Drew Bledsoe|  2005|   8|         19|      24|        220.0|          1|          0.0|
|       Drew Bledsoe|  2005|  10|         17|      24|        196.0|          1|          1.0|
|       Drew Bledsoe|  2005|  11|         12|      23|        110.0|          0|          0.0|
|       Drew Bledsoe|  2005|  12|         29|      44|        232.0|          2|          2.0|
|       Drew Bledsoe|  2005|  13|         15|      39|        146.0|          1|          2.0|
|       Drew Bledsoe|  2005|  14|         22|      34|        332.0|          3|          0.0|
|       Drew Bledsoe|  2005|  15|         16|      29|        153.0|          1|          3.0|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
only showing top 20 rows

In [16]:
sql_df_stats = sql_short.groupBy(["player_display_name","season"]).agg(sum("week"), sum("completions"), sum("attempts"), sum("passing_yards"), sum("passing_tds"), sum("interceptions"), 
                                                        avg("week") , avg("completions"), avg("attempts"), avg("passing_yards"),avg("passing_tds"), avg("interceptions"))
sql_df_stats.show()

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|         avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+
|      Jake Delhomme|  2006|       99|             263|          431|            2805.0|              17|              11.0| 7.615384615384615| 20.23076923076923| 33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|
|       Jake Plummer|  2005|      144|             277|          456|            3366.0|              18|               7.0|               9.0|           17.3125|              28.5|           210.375|             1.125|            0.4375|
|        Matt Schaub|  2006|       60|              18|           27|             208.0|               1|               2.0|              12.0|               3.6|               5.4|              41.6|               0.2|               0.4|
|        Vince Young|  2006|      143|             184|          356|            2199.0|              12|              13.0| 9.533333333333333|12.266666666666667|23.733333333333334|             146.6|               0.8|0.8666666666666667|
|      Kerry Collins|  2007|       48|              50|           82|             531.0|               0|               0.0|               8.0| 8.333333333333334|13.666666666666666|              88.5|               0.0|               0.0|
|       Todd Collins|  2005|       11|               0|            0|               0.0|               0|               0.0|              11.0|               0.0|               0.0|               0.0|               0.0|               0.0|
|      Charlie Batch|  2006|       71|              30|           52|             477.0|               5|               0.0|10.142857142857142| 4.285714285714286| 7.428571428571429| 68.14285714285714|0.7142857142857143|               0.0|
|        Eli Manning|  2006|      149|             301|          522|            3244.0|              25|              18.0|            9.3125|           18.8125|            32.625|            202.75|            1.5625|             1.125|
|        A.J. Feeley|  2006|       29|              26|           38|             342.0|               3|               0.0|              14.5|              13.0|              19.0|             171.0|               1.5|               0.0|
|       Mark Brunell|  2006|       64|             162|          261|            1789.0|               8|               4.0|               6.4|              16.2|              26.1|             178.9|               0.8|               0.4|
|         Shaun Hill|  2007|       45|              54|           80|             501.0|               5|               2.0|              15.0|              18.0|26.666666666666668|             167.0|1.6666666666666667|0.6666666666666666|
|       Aaron Brooks|  2006|       85|             110|          192|            1105.0|               3|               8.0|            10.625|             13.75|              24.0|           138.125|             0.375|               1.0|
|        Brett Favre|  2006|      147|             343|          613|            3885.0|              18|              18.0|            9.1875|           21.4375|           38.3125|          242.8125|             1.125|             1.125|
|         Drew Brees|  2007|      149|             443|          655|            4428.0|              28|              18.0|            9.3125|           27.6875|           40.9375|            276.75|              1.75|             1.125|
|   Bruce Gradkowski|  2006|      114|             177|          328|            1661.0|               9|               9.0|  8.76923076923077|13.615384615384615| 25.23076923076923|127.76923076923077|0.6923076923076923|0.6923076923076923|
|    Matt Hasselbeck|  2005|      145|             294|          450|            3455.0|              24|              10.0|            9.0625|            18.375|            28.125|          215.9375|               1.5|             0.625|
|          Tony Romo|  2005|        5|               0|            0|               0.0|               0|               0.0|               5.0|               0.0|               0.0|               0.0|               0.0|               0.0|
|     Patrick Ramsey|  2005|       32|              15|           25|             279.0|               1|               1.0|               8.0|              3.75|              6.25|             69.75|              0.25|              0.25|
|       Tommy Maddox|  2005|       27|              34|           71|             406.0|               2|               4.0|               9.0|11.333333333333334|23.666666666666668|135.33333333333334|0.6666666666666666|1.3333333333333333|
|       Jamie Martin|  2006|       17|              16|           24|             208.0|               1|               1.0|              17.0|              16.0|              24.0|             208.0|               1.0|               1.0|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+
only showing top 20 rows

In [26]:
sql_df_stats = sql_df_stats.withColumnRenamed('sum(week)', 'sum_week').withColumnRenamed("sum(completions)", "sum_completions").withColumnRenamed("sum(attempts)","sum_attempts").withColumnRenamed("sum(passing_yards)","sum_passing_yards").withColumnRenamed("sum(passing_tds)","sum_passing_tds").withColumnRenamed("sum(interceptions)","sum_interceptions").withColumnRenamed("avg(week)","avg_week").withColumnRenamed("avg(completions)","avg_completions").withColumnRenamed("avg(attempts)","avg_attempts").withColumnRenamed("avg(passing_yards)","avg_passing_yards").withColumnRenamed("avg(passing_tds)","avg_passing_tds").withColumnRenamed("avg(interceptions)","avg_interceptions")

In [27]:
sql_df_stats.columns

['player_display_name',
 'season',
 'sum_week',
 'sum_completions',
 'sum_attempts',
 'sum_passing_yards',
 'sum_passing_tds',
 'sum_interceptions',
 'avg_week',
 'avg_completions',
 'avg_attempts',
 'avg_passing_yards',
 'avg_passing_tds',
 'avg_interceptions']

In [30]:
sql_df_stats = sql_df_stats.withColumn('completion_percentage', sql_df_stats.sum_completions / sql_df_stats.sum_attempts)
sql_df_stats = sql_df_stats.withColumn('td_int_ratio', sql_df_stats.sum_passing_tds / sql_df_stats.sum_interceptions)
sql_df_stats.show(3)

+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum_week|sum_completions|sum_attempts|sum_passing_yards|sum_passing_tds|sum_interceptions|         avg_week|  avg_completions|     avg_attempts| avg_passing_yards|   avg_passing_tds| avg_interceptions|completion_percentage|      td_int_ratio|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|      99|            263|         431|           2805.0|             17|             11.0|7.615384615384615|20.23076923076923|33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|     144|            277|         456|           3366.0|             18|              7.0|              9.0|          17.3125|             28.5|           210.375|             1.125|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Matt Schaub|  2006|      60|             18|          27|            208.0|              1|              2.0|             12.0|              3.6|              5.4|              41.6|               0.2|               0.4|   0.6666666666666666|               0.5|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+-----------------+-----------------+-----------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 3 rows

In [32]:
sql_df_above_50 = sql_df_stats.where(sql_df_stats.sum_attempts >= 50) 
sql_df_above_50.show()

+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum_week|sum_completions|sum_attempts|sum_passing_yards|sum_passing_tds|sum_interceptions|          avg_week|   avg_completions|      avg_attempts| avg_passing_yards|   avg_passing_tds| avg_interceptions|completion_percentage|      td_int_ratio|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|      99|            263|         431|           2805.0|             17|             11.0| 7.615384615384615| 20.23076923076923| 33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|     144|            277|         456|           3366.0|             18|              7.0|               9.0|           17.3125|              28.5|           210.375|             1.125|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Vince Young|  2006|     143|            184|         356|           2199.0|             12|             13.0| 9.533333333333333|12.266666666666667|23.733333333333334|             146.6|               0.8|0.8666666666666667|   0.5168539325842697|0.9230769230769231|
|      Kerry Collins|  2007|      48|             50|          82|            531.0|              0|              0.0|               8.0| 8.333333333333334|13.666666666666666|              88.5|               0.0|               0.0|   0.6097560975609756|              NULL|
|      Charlie Batch|  2006|      71|             30|          52|            477.0|              5|              0.0|10.142857142857142| 4.285714285714286| 7.428571428571429| 68.14285714285714|0.7142857142857143|               0.0|   0.5769230769230769|              NULL|
|        Eli Manning|  2006|     149|            301|         522|           3244.0|             25|             18.0|            9.3125|           18.8125|            32.625|            202.75|            1.5625|             1.125|   0.5766283524904214|1.3888888888888888|
|       Mark Brunell|  2006|      64|            162|         261|           1789.0|              8|              4.0|               6.4|              16.2|              26.1|             178.9|               0.8|               0.4|   0.6206896551724138|               2.0|
|         Shaun Hill|  2007|      45|             54|          80|            501.0|              5|              2.0|              15.0|              18.0|26.666666666666668|             167.0|1.6666666666666667|0.6666666666666666|                0.675|               2.5|
|       Aaron Brooks|  2006|      85|            110|         192|           1105.0|              3|              8.0|            10.625|             13.75|              24.0|           138.125|             0.375|               1.0|   0.5729166666666666|             0.375|
|        Brett Favre|  2006|     147|            343|         613|           3885.0|             18|             18.0|            9.1875|           21.4375|           38.3125|          242.8125|             1.125|             1.125|   0.5595432300163132|               1.0|
|         Drew Brees|  2007|     149|            443|         655|           4428.0|             28|             18.0|            9.3125|           27.6875|           40.9375|            276.75|              1.75|             1.125|   0.6763358778625954|1.5555555555555556|
|   Bruce Gradkowski|  2006|     114|            177|         328|           1661.0|              9|              9.0|  8.76923076923077|13.615384615384615| 25.23076923076923|127.76923076923077|0.6923076923076923|0.6923076923076923|   0.5396341463414634|               1.0|
|    Matt Hasselbeck|  2005|     145|            294|         450|           3455.0|             24|             10.0|            9.0625|            18.375|            28.125|          215.9375|               1.5|             0.625|   0.6533333333333333|               2.4|
|       Tommy Maddox|  2005|      27|             34|          71|            406.0|              2|              4.0|               9.0|11.333333333333334|23.666666666666668|135.33333333333334|0.6666666666666666|1.3333333333333333|   0.4788732394366197|               0.5|
|      Jake Delhomme|  2007|       6|             55|          86|            617.0|              8|              1.0|               2.0|18.333333333333332|28.666666666666668|205.66666666666666|2.6666666666666665|0.3333333333333333|   0.6395348837209303|               8.0|
|       Mark Brunell|  2005|     150|            262|         454|           3050.0|             23|             10.0|             9.375|            16.375|            28.375|           190.625|            1.4375|             0.625|   0.5770925110132159|               2.3|
|        Marc Bulger|  2007|     106|            221|         378|           2392.0|             11|             15.0| 8.833333333333334|18.416666666666668|              31.5|199.33333333333334|0.9166666666666666|              1.25|   0.5846560846560847|0.7333333333333333|
|      David Garrard|  2007|     105|            208|         325|           2509.0|             18|              3.0|              8.75|17.333333333333332|27.083333333333332|209.08333333333334|               1.5|              0.25|                 0.64|               6.0|
|        Kurt Warner|  2005|      90|            242|         375|           2713.0|             11|              9.0|               9.0|              24.2|              37.5|             271.3|               1.1|               0.9|   0.6453333333333333|1.2222222222222223|
|      Kelly Holcomb|  2007|      15|             42|          83|            511.0|              2|              1.0|               5.0|              14.0|27.666666666666668|170.33333333333334|0.6666666666666666|0.3333333333333333|   0.5060240963855421|               2.0|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 20 rows

In [33]:
descending_cp = sql_df_stats.sort(sql_df_stats.completion_percentage, ascending = False)
descending_cp.show(3)

+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+--------+------------------+------------------+------------------+---------------+-----------------+---------------------+------------+
|player_display_name|season|sum_week|sum_completions|sum_attempts|sum_passing_yards|sum_passing_tds|sum_interceptions|avg_week|   avg_completions|      avg_attempts| avg_passing_yards|avg_passing_tds|avg_interceptions|completion_percentage|td_int_ratio|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+--------+------------------+------------------+------------------+---------------+-----------------+---------------------+------------+
|     Matt Gutierrez|  2007|      18|              1|           1|             15.0|              0|              0.0|     4.5|              0.25|              0.25|              3.75|            0.0|              0.0|                  1.0|        NULL|
|        Billy Volek|  2010|      21|              1|           1|              8.0|              0|              0.0|     7.0|0.3333333333333333|0.3333333333333333|2.6666666666666665|            0.0|              0.0|                  1.0|        NULL|
|     Matt Gutierrez|  2009|       7|              1|           1|              3.0|              0|              0.0|     7.0|               1.0|               1.0|               3.0|            0.0|              0.0|                  1.0|        NULL|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+--------+------------------+------------------+------------------+---------------+-----------------+---------------------+------------+
only showing top 3 rows

In [34]:
ascending_td = sql_df_stats.sort(sql_df_stats.td_int_ratio)
ascending_td.show()

+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+------------------+------------------+-----------------+------------------+------------------+-----------------+---------------------+------------+
|player_display_name|season|sum_week|sum_completions|sum_attempts|sum_passing_yards|sum_passing_tds|sum_interceptions|          avg_week|   avg_completions|     avg_attempts| avg_passing_yards|   avg_passing_tds|avg_interceptions|completion_percentage|td_int_ratio|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+------------------+------------------+-----------------+------------------+------------------+-----------------+---------------------+------------+
|         Brad Smith|  2006|     129|              0|           0|              0.0|              0|              0.0| 9.923076923076923|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|         Quinn Gray|  2005|      17|              8|          14|            100.0|              2|              0.0|              17.0|               8.0|             14.0|             100.0|               2.0|              0.0|   0.5714285714285714|        NULL|
|        Jay Fiedler|  2005|       4|              8|          13|            107.0|              1|              0.0|               2.0|               4.0|              6.5|              53.5|               0.5|              0.0|   0.6153846153846154|        NULL|
|        Josh McCown|  2006|      13|              0|           0|              0.0|              0|              0.0|              13.0|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|    Kliff Kingsbury|  2005|      11|              1|           2|             17.0|              0|              0.0|              11.0|               1.0|              2.0|              17.0|               0.0|              0.0|                  0.5|        NULL|
|      Charlie Batch|  2006|      71|             30|          52|            477.0|              5|              0.0|10.142857142857142| 4.285714285714286|7.428571428571429| 68.14285714285714|0.7142857142857143|              0.0|   0.5769230769230769|        NULL|
|       Chris Weinke|  2005|      31|              7|          13|             64.0|              1|              0.0|10.333333333333334|2.3333333333333335|4.333333333333333|21.333333333333332|0.3333333333333333|              0.0|   0.5384615384615384|        NULL|
|          Tony Romo|  2005|       5|              0|           0|              0.0|              0|              0.0|               5.0|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|          Jim Sorgi|  2007|      55|             18|          36|            132.0|              1|              0.0|             13.75|               4.5|              9.0|              33.0|              0.25|              0.0|                  0.5|        NULL|
|       Jamie Martin|  2007|      12|              0|           0|              0.0|              0|              0.0|              12.0|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|   Bradlee Van Pelt|  2005|      30|              2|           8|              7.0|              0|              0.0|              15.0|               1.0|              4.0|               3.5|               0.0|              0.0|                 0.25|        NULL|
|       Ingle Martin|  2006|      17|              0|           0|              0.0|              0|              0.0|              17.0|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|         Quinn Gray|  2006|      17|             13|          22|            166.0|              0|              0.0|              17.0|              13.0|             22.0|             166.0|               0.0|              0.0|   0.5909090909090909|        NULL|
|   Ryan Fitzpatrick|  2006|      17|              0|           0|              0.0|              0|              0.0|              17.0|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|     Jared Lorenzen|  2007|       3|              4|           8|             28.0|              0|              0.0|               1.5|               2.0|              4.0|              14.0|               0.0|              0.0|                  0.5|        NULL|
|     Anthony Wright|  2006|      26|              3|           3|             31.0|              0|              0.0|              13.0|               1.5|              1.5|              15.5|               0.0|              0.0|                  1.0|        NULL|
|     Kellen Clemens|  2006|      19|              0|           1|              0.0|              0|              0.0|               9.5|               0.0|              0.5|               0.0|               0.0|              0.0|                  0.0|        NULL|
|         Shaun Hill|  2005|      17|              0|           0|              0.0|              0|              0.0|              17.0|               0.0|              0.0|               0.0|               0.0|              0.0|                 NULL|        NULL|
|       Dan Orlovsky|  2005|      14|              7|          17|             63.0|              0|              0.0|               7.0|               3.5|              8.5|              31.5|               0.0|              0.0|   0.4117647058823529|        NULL|
|       Todd Collins|  2007|      62|             67|         105|            888.0|              5|              0.0|              15.5|             16.75|            26.25|             222.0|              1.25|              0.0|    0.638095238095238|        NULL|
+-------------------+------+--------+---------------+------------+-----------------+---------------+-----------------+------------------+------------------+-----------------+------------------+------------------+-----------------+---------------------+------------+
only showing top 20 rows

In [ ]:
sql_df_stats.select(['sum_passing_tds','sum_interceptions', 'td_int_ratio']).show()